"""`svg_normalize.normalize_svg` (Q3): prologo, rifiuti, radice in px.

Test puro. La scansione dei pattern `href=` / `url(` / `on*=` è limitata al
contenuto dei tag: una label «vedi url(x)» o un tick «href=» in un nodo di
testo sono contenuti legittimi (correzione WP2b).
"""

from __future__ import annotations

import base64

import pytest

from app.services.svg_normalize import (
    SVG_NS,
    NormalizedSvg,
    SvgRejectedError,
    normalize_svg,
    svg_base_font_px,
    svg_intrinsic_box,
    svg_to_data_uri,
)

_GRAPHVIZ = (
    '<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n'
    '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"\n'
    ' "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">\n'
    "<!-- Generated by graphviz version 15.1.1 (0)\n -->\n"
    "<!-- Title: G Pages: 1 -->\n"
    '<svg width="62pt" height="116pt"\n viewBox="0.00 0.00 62.00 116.00" '
    'xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">\n'
    '<g id="graph0" class="graph"><title>G</title>'
    '<text text-anchor="middle" x="31" y="20">vedi url(x)</text></g></svg>\n'
)

_MATPLOTLIB = (
    '<?xml version="1.0" encoding="utf-8" standalone="no"?>\n'
    '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" '
    '"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">\n'
    "<!-- Created with matplotlib (https://matplotlib.org/) -->\n"
    '<svg xmlns:xlink="http://www.w3.org/1999/xlink" width="374.4pt" height="259.2pt" '
    'viewBox="0 0 374.4 259.2" xmlns="http://www.w3.org/2000/svg" version="1.1">\n'
    '<defs><clipPath id="p1"><rect x="0" y="0" width="10" height="10"/></clipPath>'
    '<path id="m1" d="M 0 0 L 1 1"/></defs>'
    '<g clip-path="url(#p1)"><use xlink:href="#m1" x="1" y="1"/></g></svg>'
)


def test_prologue_doctype_and_leading_comments_are_stripped():
    out = normalize_svg(_GRAPHVIZ, max_bytes=100_000)
    assert isinstance(out, NormalizedSvg)
    assert out.svg.startswith("<svg ")
    assert "<?xml" not in out.svg and "DOCTYPE" not in out.svg
    assert "Generated by graphviz" not in out.svg and "Title:" not in out.svg
    assert out.svg.endswith("</svg>")


def test_pt_sizes_become_px_and_viewbox_is_preserved():
    out = normalize_svg(_GRAPHVIZ, max_bytes=100_000)
    assert out.width_px == pytest.approx(62 * 96 / 72)
    assert out.height_px == pytest.approx(116 * 96 / 72)
    assert 'width="82.67"' in out.svg and 'height="154.67"' in out.svg
    assert 'viewBox="0 0 62 116"' in out.svg
    assert 'preserveAspectRatio="xMidYMid meet"' in out.svg
    assert out.svg.count("<svg") == 1


def test_matplotlib_374pt_becomes_499px_and_internal_use_and_clippath_pass():
    out = normalize_svg(_MATPLOTLIB, max_bytes=100_000)
    assert out.width_px == pytest.approx(499.2)
    assert out.height_px == pytest.approx(345.6)
    assert 'width="499.2"' in out.svg
    assert '<use xlink:href="#m1"' in out.svg and "clipPath" in out.svg
    assert 'clip-path="url(#p1)"' in out.svg
    assert "Created with matplotlib" not in out.svg


def test_viewbox_is_built_from_width_and_height_when_absent():
    out = normalize_svg('<svg width="120" height="80"><rect/></svg>', max_bytes=10_000)
    assert 'viewBox="0 0 120 80"' in out.svg
    assert out.width_px == 120 and out.height_px == 80


def test_sizes_are_derived_from_viewbox_when_absent():
    out = normalize_svg('<svg viewBox="0 0 300 150"><rect/></svg>', max_bytes=10_000)
    assert out.width_px == 300 and out.height_px == 150
    assert 'width="300"' in out.svg and 'height="150"' in out.svg


def test_xmlns_is_guaranteed_and_max_width_removed_from_style():
    raw = '<svg width="10" height="10" style="max-width: 300px; background: white"><g/></svg>'
    out = normalize_svg(raw, max_bytes=10_000)
    assert f'xmlns="{SVG_NS}"' in out.svg
    assert "max-width" not in out.svg and 'style="background: white"' in out.svg


def test_mm_and_in_units_are_converted():
    out = normalize_svg('<svg width="25.4mm" height="1in"><g/></svg>', max_bytes=10_000)
    assert out.width_px == pytest.approx(96) and out.height_px == pytest.approx(96)


def test_percent_width_is_ignored_and_viewbox_wins():
    out = normalize_svg('<svg width="100%" viewBox="0 0 40 20"><g/></svg>', max_bytes=10_000)
    assert out.width_px == 40 and out.height_px == 20


def test_size_cap_is_enforced():
    with pytest.raises(SvgRejectedError, match="oltre"):
        normalize_svg("<svg>" + "x" * 100 + "</svg>", max_bytes=50)


def test_missing_root_is_rejected():
    with pytest.raises(SvgRejectedError, match="radice"):
        normalize_svg("<div>non svg</div>", max_bytes=10_000)


@pytest.mark.parametrize(
    ("svg", "label"),
    [
        ("<svg><script>alert(1)</script></svg>", "script"),
        ("<svg><foreignObject><div>x</div></foreignObject></svg>", "foreignObject"),
        ('<svg><iframe src="x"/></svg>', "iframe"),
        ('<svg><image href="#a"/></svg>', "image"),
        ('<svg><image xlink:href="data:image/png;base64,AA"/></svg>', "image"),
        ('<svg><use href="http://x/y.svg#a"/></svg>', "use con href esterno"),
        ('<svg><g onclick="x()"/></svg>', "gestore di evento"),
        ('<svg><a href="http://x"><text>t</text></a></svg>', "href esterno"),
        ('<svg><a xlink:href="javascript:alert(1)"><text>t</text></a></svg>', "href esterno"),
        ("<svg><a href=http://x><text>t</text></a></svg>", "href esterno"),  # non quotato
        ("<svg><use href=http://x/y.svg/></svg>", "use con href esterno"),
        ('<svg><set attributeName="onclick" to="alert(1)"/></svg>', "set"),
        ('<svg><a><animate attributeName="href" values="javascript:x"/></a></svg>', "animate"),
        ('<svg><rect><animateTransform attributeName="transform"/></rect></svg>', "animate"),
        ('<svg><handler type="text/ecmascript"/></svg>', "handler"),
        # Nome con prefisso di namespace: stesso elemento per un parser XML.
        ("<svg><svg:script>x</svg:script></svg>", "script"),
        ("<svg><x:foreignObject><div>x</div></x:foreignObject></svg>", "foreignObject"),
        ('<svg><a:image href="#a"/></svg>', "image"),
        ('<svg><s:set attributeName="onclick" to="x"/></svg>', "set"),
        ('<svg><g style="background:url(http://x)"/></svg>', "url() esterno"),
        ("<svg><style>@import url(http://x/a.css);</style></svg>", "@import in <style>"),
        (
            "<svg><style>.a{background:url(http://x/a.png)}</style></svg>",
            "url() esterno in <style>",
        ),
    ],
)
def test_forbidden_content_is_rejected(svg: str, label: str):
    with pytest.raises(SvgRejectedError) as exc:
        normalize_svg(svg, max_bytes=10_000)
    assert label in str(exc.value)


def test_text_nodes_are_not_scanned():
    """Label e tick con `url(`, `href=`, `javascript:` o `onload=` nel TESTO
    sono legittimi: la scansione vale solo per gli attributi."""
    raw = (
        '<svg width="10" height="10"><text>vedi url(x)</text><text>href=</text>'
        "<title>javascript: e onload= nel titolo</title>"
        "<text>@import e data:text/html citati</text></svg>"
    )
    out = normalize_svg(raw, max_bytes=10_000)
    assert "vedi url(x)" in out.svg and "href=" in out.svg


def test_aria_attributes_are_inert_text():
    raw = (
        '<svg width="10" height="10">'
        '<g aria-label="Title text \'vedi url(x)\'" role="graphics-symbol">'
        '<path aria-label="k: onload=; v: 3" aria-roledescription="bar" d="M0,0"/></g></svg>'
    )
    out = normalize_svg(raw, max_bytes=10_000)
    assert "aria-label" in out.svg  # non rimossi, solo esclusi dalla scansione
    with pytest.raises(SvgRejectedError, match="gestore di evento"):
        normalize_svg('<svg><g aria-label="x" onload="y()"/></svg>', max_bytes=10_000)


def test_fragment_references_in_attributes_are_allowed():
    raw = (
        '<svg width="10" height="10"><a href="#sezione"><text>t</text></a>'
        "<a href=#nudo><text>u</text></a>"
        '<g style="clip-path:url(#c)" fill="url( \'#grad\' )"/></svg>'
    )
    out = normalize_svg(raw, max_bytes=10_000)
    assert 'href="#sezione"' in out.svg and "href=#nudo" in out.svg


def test_tag_scan_respects_quotes():
    """Un `>` dentro un valore quotato non chiude il tag: gli attributi che
    seguono (`onclick=`) restano nella scansione. Vega emette `&gt;`, ma il
    modulo non deve dipendere da questo."""
    for raw in (
        '<svg><text aria-label="a > b" onclick="x">t</text></svg>',
        '<svg><text aria-label=\'a "b" > c\' onclick="x">t</text></svg>',
        '<svg><text>it\'s</text><g onclick="x"/></svg>',
    ):
        with pytest.raises(SvgRejectedError, match="gestore di evento"):
            normalize_svg(raw, max_bytes=10_000)
    out = normalize_svg('<svg><text aria-label="a > b">t</text><settings/></svg>', max_bytes=10_000)
    assert 'aria-label="a > b"' in out.svg  # `<settings` non è `<set`


def test_scannable_regions_are_shared_with_the_mermaid_check():
    """`iter_tag_contents` e `iter_style_bodies` sono la parte «codice» di
    un SVG: gli attributi e il CSS, mai il testo dei nodi. Le usa anche il
    controllo degli SVG Mermaid, che non passano da `normalize_svg`."""
    from app.services.svg_normalize import iter_style_bodies, iter_tag_contents

    svg = (
        "<svg><style>.a{fill:red}</style>"
        '<text aria-label="url(https://a)">@import e url(https://b)</text></svg>'
    )
    tags = list(iter_tag_contents(svg))
    assert tags[0] == "<svg>" and tags[-1] == "</svg>"
    joined = "".join(tags)
    assert "@import" not in joined  # testo del nodo
    assert "https://a" not in joined  # attributo `aria-*`
    assert list(iter_style_bodies(svg)) == [".a{fill:red}"]


def test_svg_to_data_uri_is_base64():
    svg = '<svg xmlns="http://www.w3.org/2000/svg"/>'
    uri = svg_to_data_uri(svg)
    assert uri.startswith("data:image/svg+xml;base64,")
    assert base64.b64decode(uri.split(",", 1)[1]).decode("utf-8") == svg


# ---------------------------------------------------------------------------
# Letture per la banda di leggibilità (D10): `svg_intrinsic_box`, `svg_base_font_px`
# ---------------------------------------------------------------------------


def test_intrinsic_box_of_a_normalized_svg_matches_the_normalizer():
    """`px_per_unit` è la scala fra le unità utente (pt per DOT e matplotlib)
    e i px riscritti da `normalize_svg`; le due letture non toccano l'SVG."""
    raw = (
        '<svg width="83pt" height="213pt" viewBox="0 0 83 213">'
        '<text font-size="10.00">a</text></svg>'
    )
    normalized = normalize_svg(raw, max_bytes=10_000)
    box = svg_intrinsic_box(normalized.svg)
    assert box is not None
    # La radice riscritta porta i px arrotondati al centesimo (`_fmt`).
    assert box.width_px == pytest.approx(normalized.width_px, abs=0.01)
    assert box.height_px == pytest.approx(normalized.height_px, abs=0.01)
    assert box.px_per_unit == pytest.approx(4 / 3, abs=1e-3)
    metrics = svg_base_font_px(normalized.svg)
    assert metrics.font_px_min == pytest.approx(10 * box.px_per_unit)
    assert metrics.source == "parsed"
    assert normalize_svg(normalized.svg, max_bytes=10_000).svg == normalized.svg  # idempotente


def test_root_rule_must_be_exact_and_data_attributes_are_ignored():
    # `#m svg{…}` non è la regola radice: senza `#m{…}` il testo resta irrisolto.
    only_descendant = '<svg id="m"><style>#m svg{font-size:20px}</style><text>x</text></svg>'
    assert svg_base_font_px(only_descendant).source == "unresolved"
    # `#mm{…}` non è `#m{…}`; `#m{…}` preceduto da `}` sì.
    longer_id = (
        '<svg id="m"><style>#mm{font-size:9px}.a{}#m{font-size:14px}</style><text>x</text></svg>'
    )
    assert svg_base_font_px(longer_id).font_px_min == 14.0
    assert (
        svg_base_font_px('<svg><text data-font-size="99" font-size="10">a</text></svg>').font_px_min
        == 10.0
    )
    # Con lo `style` presente ma relativo, l'attributo non fa da ripiego (precedenza CSS).
    relative = '<svg><text style="font-size:1.2em" font-size="10">a</text></svg>'
    assert svg_base_font_px(relative).source == "unresolved"
    # Il minimo viene dal valore proprio anche a parità con la radice.
    tie = (
        '<svg id="m"><style>#m{font-size:14px}</style>'
        '<text font-size="14">a</text><text>b</text></svg>'
    )
    assert svg_base_font_px(tie).source == "parsed"


def _min_px(svg: str) -> float | None:
    return svg_base_font_px(svg).font_px_min


def test_style_cascade_follows_css_for_the_covered_selectors():
    """Ripiego della misura Mermaid (F1 di WP3): le regole del `<style>` per
    classe, discendenza e figlio diretto valgono come in Chromium, con
    specificità e ordine; `#m svg` vale solo per un `<svg>` annidato."""
    child = (
        '<svg id="m"><style>#m{font-size:14px}#m .g>text{font-size:9px}</style>'
        '<g class="g"><g><text>lontano</text></g></g></svg>'
    )
    assert _min_px(child) == 14.0  # `>` richiede il figlio diretto
    direct = child.replace("<g><text>lontano</text></g>", "<text>vicino</text>")
    assert _min_px(direct) == 9.0
    specific = (
        '<svg id="m"><style>#m g.k text{font-size:18px}#m .t{font-size:9px}</style>'
        '<g class="k"><text class="t">a</text></g></svg>'
    )
    assert _min_px(specific) == 18.0  # (1,1,2) batte (1,1,0) anche se precede
    later = '<svg id="m"><style>#m .t{font-size:9px}#m .t{font-size:13px}</style>'
    assert _min_px(later + '<text class="t">a</text></svg>') == 13.0
    nested = (
        '<svg id="m"><style>#m{font-size:14px}#m svg{font-size:20px}</style>'
        "<svg><text>dentro</text></svg></svg>"
    )
    assert _min_px(nested) == 20.0
    # `>` nei selettori, commenti e CDATA nel `<style>` non rompono la scansione.
    noisy = (
        '<svg id="m"><style><![CDATA[/* a > b */ #m > g > text { font-size: 11px }]]></style>'
        "<g><text>a</text></g><text>b</text></svg>"
    )
    metrics = svg_base_font_px(noisy)
    assert (metrics.font_px_min, metrics.text_count, metrics.source) == (11.0, 2, "root_rule")


def test_size_declarations_outside_the_grammar_are_unresolved():
    """Un corpo che la cascata minima non sa attribuire non diventa mai un
    valore: la lettura è irrisolta e il fit usa la costante di formato
    (loggata). Le regole fuori grammatica senza corpo non contano."""
    text = '<text font-size="12">a</text></svg>'
    for style in (
        "#m text[x]{font-size:30px}",
        "#m g+text{font-size:30px}",
        "#m g~text{font-size:30px}",
        "#m text:not(.a){font-size:30px}",
        "@media print{#m text{font-size:30px}}",
        "@keyframes k{to{font-size:30px}}",
        "#m text{font:30px sans-serif}",
        "#m text{font-size:var(--x)}",
        "#m text{font-size:2rem}",
        "#m text{font-size:small}",
        "#m text{font-size:calc(1px + 2px)}",
        "#m{& text{font-size:30px}}",
    ):
        metrics = svg_base_font_px(f'<svg id="m"><style>{style}</style>{text}')
        assert (metrics.font_px_min, metrics.source) == (None, "unresolved"), style
    inline = '<svg><text style="font: 30px sans-serif" font-size="12">a</text></svg>'
    assert svg_base_font_px(inline).source == "unresolved"
    harmless = (
        '<svg id="m"><style>#m text:first-child{fill:red}@keyframes k{to{opacity:0}}'
        "@font-face{font-family:x}</style>" + text
    )
    assert (_min_px(harmless), svg_base_font_px(harmless).source) == (12.0, "parsed")
    # Un `font-size=` dentro il valore di un altro attributo resta valore;
    # le entità dei valori sono risolte come nel DOM.
    aria = '<svg><text aria-label="x font-size=\'2\'" font-size="12">a</text></svg>'
    assert _min_px(aria) == 12.0
    quoted = '<svg><text style="font-family: &quot;Noto Sans&quot;; font-size: 16px">a</text></svg>'
    assert _min_px(quoted) == 16.0


def test_text_nodes_are_read_like_the_dom():
    """Stessa definizione di «testo proprio» di `__measureSvgFontPx`: un nodo
    di testo figlio diretto non vuoto; i tag autochiusi e i commenti non
    contano, il prefisso di namespace sì."""
    svg = (
        '<svg xmlns:svg="http://www.w3.org/2000/svg">'
        '<text font-size="7"/><text font-size="6"><!-- nota --></text>'
        '<svg:text font-size="15">a</svg:text><text font-size="13">  <tspan>b</tspan></text>'
        "</svg>"
    )
    metrics = svg_base_font_px(svg)
    assert (metrics.font_px_min, metrics.text_count) == (13.0, 2)
    # Il `tspan` senza valore eredita 13 dal padre: il minimo resta 13.
    assert metrics.font_px_median == 14.0


def test_exports_include_the_readers():
    from app.services import svg_normalize

    assert {"SvgBox", "svg_intrinsic_box", "svg_base_font_px"} <= set(svg_normalize.__all__)
