"""`svg_normalize.normalize_svg` (Q3): prologo, rifiuti, radice in px.

Test puro. La scansione dei pattern `href=` / `url(` / `on*=` è limitata al
contenuto dei tag: una label «vedi url(x)» o un tick «href=» in un nodo di
testo sono contenuti legittimi (correzione WP2b).
"""

from __future__ import annotations

import base64

import pytest

from app.services.svg_normalize import (
    SVG_NS,
    NormalizedSvg,
    SvgRejectedError,
    normalize_svg,
    svg_to_data_uri,
)

_GRAPHVIZ = (
    '<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n'
    '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"\n'
    ' "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">\n'
    "<!-- Generated by graphviz version 15.1.1 (0)\n -->\n"
    "<!-- Title: G Pages: 1 -->\n"
    '<svg width="62pt" height="116pt"\n viewBox="0.00 0.00 62.00 116.00" '
    'xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">\n'
    '<g id="graph0" class="graph"><title>G</title>'
    '<text text-anchor="middle" x="31" y="20">vedi url(x)</text></g></svg>\n'
)

_MATPLOTLIB = (
    '<?xml version="1.0" encoding="utf-8" standalone="no"?>\n'
    '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" '
    '"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">\n'
    "<!-- Created with matplotlib (https://matplotlib.org/) -->\n"
    '<svg xmlns:xlink="http://www.w3.org/1999/xlink" width="374.4pt" height="259.2pt" '
    'viewBox="0 0 374.4 259.2" xmlns="http://www.w3.org/2000/svg" version="1.1">\n'
    '<defs><clipPath id="p1"><rect x="0" y="0" width="10" height="10"/></clipPath>'
    '<path id="m1" d="M 0 0 L 1 1"/></defs>'
    '<g clip-path="url(#p1)"><use xlink:href="#m1" x="1" y="1"/></g></svg>'
)


def test_prologue_doctype_and_leading_comments_are_stripped():
    out = normalize_svg(_GRAPHVIZ, max_bytes=100_000)
    assert isinstance(out, NormalizedSvg)
    assert out.svg.startswith("<svg ")
    assert "<?xml" not in out.svg and "DOCTYPE" not in out.svg
    assert "Generated by graphviz" not in out.svg and "Title:" not in out.svg
    assert out.svg.endswith("</svg>")


def test_pt_sizes_become_px_and_viewbox_is_preserved():
    out = normalize_svg(_GRAPHVIZ, max_bytes=100_000)
    assert out.width_px == pytest.approx(62 * 96 / 72)
    assert out.height_px == pytest.approx(116 * 96 / 72)
    assert 'width="82.67"' in out.svg and 'height="154.67"' in out.svg
    assert 'viewBox="0 0 62 116"' in out.svg
    assert 'preserveAspectRatio="xMidYMid meet"' in out.svg
    assert out.svg.count("<svg") == 1


def test_matplotlib_374pt_becomes_499px_and_internal_use_and_clippath_pass():
    out = normalize_svg(_MATPLOTLIB, max_bytes=100_000)
    assert out.width_px == pytest.approx(499.2)
    assert out.height_px == pytest.approx(345.6)
    assert 'width="499.2"' in out.svg
    assert '<use xlink:href="#m1"' in out.svg and "clipPath" in out.svg
    assert 'clip-path="url(#p1)"' in out.svg
    assert "Created with matplotlib" not in out.svg


def test_viewbox_is_built_from_width_and_height_when_absent():
    out = normalize_svg('<svg width="120" height="80"><rect/></svg>', max_bytes=10_000)
    assert 'viewBox="0 0 120 80"' in out.svg
    assert out.width_px == 120 and out.height_px == 80


def test_sizes_are_derived_from_viewbox_when_absent():
    out = normalize_svg('<svg viewBox="0 0 300 150"><rect/></svg>', max_bytes=10_000)
    assert out.width_px == 300 and out.height_px == 150
    assert 'width="300"' in out.svg and 'height="150"' in out.svg


def test_xmlns_is_guaranteed_and_max_width_removed_from_style():
    raw = '<svg width="10" height="10" style="max-width: 300px; background: white"><g/></svg>'
    out = normalize_svg(raw, max_bytes=10_000)
    assert f'xmlns="{SVG_NS}"' in out.svg
    assert "max-width" not in out.svg and 'style="background: white"' in out.svg


def test_mm_and_in_units_are_converted():
    out = normalize_svg('<svg width="25.4mm" height="1in"><g/></svg>', max_bytes=10_000)
    assert out.width_px == pytest.approx(96) and out.height_px == pytest.approx(96)


def test_percent_width_is_ignored_and_viewbox_wins():
    out = normalize_svg('<svg width="100%" viewBox="0 0 40 20"><g/></svg>', max_bytes=10_000)
    assert out.width_px == 40 and out.height_px == 20


def test_size_cap_is_enforced():
    with pytest.raises(SvgRejectedError, match="oltre"):
        normalize_svg("<svg>" + "x" * 100 + "</svg>", max_bytes=50)


def test_missing_root_is_rejected():
    with pytest.raises(SvgRejectedError, match="radice"):
        normalize_svg("<div>non svg</div>", max_bytes=10_000)


@pytest.mark.parametrize(
    ("svg", "label"),
    [
        ("<svg><script>alert(1)</script></svg>", "script"),
        ("<svg><foreignObject><div>x</div></foreignObject></svg>", "foreignObject"),
        ('<svg><iframe src="x"/></svg>', "iframe"),
        ('<svg><image href="#a"/></svg>', "image"),
        ('<svg><image xlink:href="data:image/png;base64,AA"/></svg>', "image"),
        ('<svg><use href="http://x/y.svg#a"/></svg>', "use con href esterno"),
        ('<svg><g onclick="x()"/></svg>', "gestore di evento"),
        ('<svg><a href="http://x"><text>t</text></a></svg>', "href esterno"),
        ('<svg><a xlink:href="javascript:alert(1)"><text>t</text></a></svg>', "href esterno"),
        ('<svg><g style="background:url(http://x)"/></svg>', "url() esterno"),
        ("<svg><style>@import url(http://x/a.css);</style></svg>", "@import in <style>"),
        (
            "<svg><style>.a{background:url(http://x/a.png)}</style></svg>",
            "url() esterno in <style>",
        ),
    ],
)
def test_forbidden_content_is_rejected(svg: str, label: str):
    with pytest.raises(SvgRejectedError) as exc:
        normalize_svg(svg, max_bytes=10_000)
    assert label in str(exc.value)


def test_text_nodes_are_not_scanned():
    """Label e tick con `url(`, `href=`, `javascript:` o `onload=` nel TESTO
    sono legittimi: la scansione vale solo per gli attributi."""
    raw = (
        '<svg width="10" height="10"><text>vedi url(x)</text><text>href=</text>'
        "<title>javascript: e onload= nel titolo</title>"
        "<text>@import e data:text/html citati</text></svg>"
    )
    out = normalize_svg(raw, max_bytes=10_000)
    assert "vedi url(x)" in out.svg and "href=" in out.svg


def test_aria_attributes_are_inert_text():
    raw = (
        '<svg width="10" height="10">'
        '<g aria-label="Title text \'vedi url(x)\'" role="graphics-symbol">'
        '<path aria-label="k: onload=; v: 3" aria-roledescription="bar" d="M0,0"/></g></svg>'
    )
    out = normalize_svg(raw, max_bytes=10_000)
    assert "aria-label" in out.svg  # non rimossi, solo esclusi dalla scansione
    with pytest.raises(SvgRejectedError, match="gestore di evento"):
        normalize_svg('<svg><g aria-label="x" onload="y()"/></svg>', max_bytes=10_000)


def test_fragment_references_in_attributes_are_allowed():
    raw = (
        '<svg width="10" height="10"><a href="#sezione"><text>t</text></a>'
        '<g style="clip-path:url(#c)" fill="url( \'#grad\' )"/></svg>'
    )
    out = normalize_svg(raw, max_bytes=10_000)
    assert 'href="#sezione"' in out.svg


def test_svg_to_data_uri_is_base64():
    svg = '<svg xmlns="http://www.w3.org/2000/svg"/>'
    uri = svg_to_data_uri(svg)
    assert uri.startswith("data:image/svg+xml;base64,")
    assert base64.b64decode(uri.split(",", 1)[1]).decode("utf-8") == svg
