"""Normalizzazione degli SVG prodotti dai renderer server-side (Q3).

Modulo puro (regex sul solo tag radice + scansione del documento): nessun
parser XML, nessuna dipendenza dal resto dell'applicazione. Vale per gli SVG
di vl-convert (Vega-Lite), Graphviz `dot` e matplotlib (`function`); gli SVG
Mermaid NON passano da qui (la loro catena resta byte-identica, A11).

Regole:
1. oltre `max_bytes` → `SvgRejectedError`;
2. prologo rimosso: BOM, `<?xml …?>`, `<!DOCTYPE …>`, commenti iniziali
   («Created with matplotlib», «Generated by graphviz»: determinismo fra
   versioni e date);
3. scansione che RIFIUTA (i renderer sono nostri: un'anomalia è un
   fallback, non una sanificazione parziale). Globale sul documento per
   gli elementi attivi, animati o esterni: `<script`, `<foreignObject`,
   `<iframe`, `<image`, `<set`, `<animate*`, `<handler` (SMIL può
   riscrivere `href` o `on*` a tempo di esecuzione; nessun renderer nostro
   li emette), anche con prefisso di namespace (`<svg:script`). Limitata
   al contenuto dei tag `<…>` (attributi) per `<use`
   con href non-frammento, gestori `on*=`, `href` esterni (quotati o no),
   `javascript:`, `data:text/html`, `@import`, `url()` non-frammento; le
   stesse regole CSS valgono dentro `<style>…</style>`. Il riconoscimento
   del tag rispetta le virgolette: un `>` dentro un valore quotato
   (`aria-label="a > b"`) non chiude il tag e gli attributi successivi
   vengono scanditi. Il testo dei nodi (label, tick, `<title>`) NON è
   scandito: una label «vedi url(x)» o un tick «href=» sono contenuti
   legittimi. I `<use xlink:href="#m…">` e i `<clipPath>` interni di
   matplotlib passano;
4. tag radice: `viewBox` letto o costruito, `width`/`height` convertiti in
   px (`pt×96/72`, `mm×96/25.4`, `in×96`) e RISCRITTI come dimensione
   intrinseca dell'`<img>` (`max-width:100%` riduce ma non ingrandisce: un
   grafo DOT a tre nodi resta piccolo), `preserveAspectRatio="xMidYMid
   meet"`, `max-width` rimosso dallo `style`, `xmlns` garantito. Nessun
   namespacing degli id: ogni `<img>` è un documento isolato.

Due letture pure per la banda di leggibilità (D10, `figure_scale`), valide
anche per gli SVG Mermaid perché non li modificano: `svg_intrinsic_box`
(viewBox, dimensione intrinseca e `px_per_unit` della radice) e
`svg_base_font_px` (corpo minimo dei testi di contenuto con una cascata
CSS minima: attributi e `style` dei `<text>`/`<tspan>`, regole del
`<style>` per id, classe e discendenza, eredità dal padre).
"""

from __future__ import annotations

import base64
import contextlib
import html
import re
import statistics
from collections.abc import Iterator
from dataclasses import dataclass

from app.services.figure_scale import MetricsSource, SvgMetrics

SVG_NS = "http://www.w3.org/2000/svg"
XLINK_NS = "http://www.w3.org/1999/xlink"


class SvgRejectedError(ValueError):
    """L'SVG non è accettabile (dimensione, contenuto attivo, radice mancante)."""


@dataclass(frozen=True)
class NormalizedSvg:
    svg: str
    width_px: float | None
    height_px: float | None


# --- prologo -------------------------------------------------------------

_PROLOGUE_RE = re.compile(
    r"^(?:\s*(?:<\?xml[^>]*\?>|<!DOCTYPE(?:[^>\[]|\[[^\]]*\])*>|<!--.*?-->))*\s*",
    re.DOTALL | re.IGNORECASE,
)

# --- scansione ----------------------------------------------------------

# Elementi rifiutati ovunque compaiano: sono attivi (script), animati
# (set, animate*, handler: SMIL può assegnare `href` o `on*` a tempo di
# esecuzione), portano HTML (foreignObject, iframe) o risorse
# esterne/raster (image). `function_plot` non produce mai `<image>`
# nonostante `svg.image_inline` nei rcParams (contour e fill_between sono
# path; niente imshow). Il nome dell'elemento può portare un prefisso di
# namespace (`<svg:script>`, `<x:foreignObject>`): stesso elemento per un
# parser XML, stesso rifiuto.
_NS_PREFIX = r"<\s*(?:[A-Za-z_][\w.-]*:)?"
_FORBIDDEN_GLOBAL: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("script", re.compile(_NS_PREFIX + r"script\b", re.IGNORECASE)),
    ("foreignObject", re.compile(_NS_PREFIX + r"foreignObject\b", re.IGNORECASE)),
    ("iframe", re.compile(_NS_PREFIX + r"iframe\b", re.IGNORECASE)),
    ("image", re.compile(_NS_PREFIX + r"image\b", re.IGNORECASE)),
    ("set", re.compile(_NS_PREFIX + r"set\b", re.IGNORECASE)),
    ("animate", re.compile(_NS_PREFIX + r"animate[a-z]*\b", re.IGNORECASE)),
    ("handler", re.compile(_NS_PREFIX + r"handler\b", re.IGNORECASE)),
)

# `href` esterno: valore quotato che non inizia con `#`, oppure valore non
# quotato (`href=http://x`) che non è un frammento.
_EXTERNAL_HREF = r"\bhref\s*=\s*(?:[\"']\s*(?!#)|(?![\"'\s#]))"

# Pattern applicati SOLO al contenuto dei tag `<…>` (attributi), non al
# testo dei nodi: una label «vedi url(x)» è testo legittimo, un attributo
# `style="…url(http://…)"` no.
_FORBIDDEN_IN_TAG: tuple[tuple[str, re.Pattern[str]], ...] = (
    (
        "use con href esterno",
        re.compile(r"^<\s*use\b[^>]*" + _EXTERNAL_HREF, re.IGNORECASE),
    ),
    ("gestore di evento", re.compile(r"(?<![\w-])on[a-z]+\s*=", re.IGNORECASE)),
    ("href esterno", re.compile(_EXTERNAL_HREF, re.IGNORECASE)),
)

# Pattern CSS/URI: valgono negli attributi e dentro i blocchi `<style>`.
_FORBIDDEN_CSS: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("javascript:", re.compile(r"javascript\s*:", re.IGNORECASE)),
    ("data:text/html", re.compile(r"data\s*:\s*text/html", re.IGNORECASE)),
    ("@import", re.compile(r"@import\b", re.IGNORECASE)),
    ("url() esterno", re.compile(r"\burl\((?!\s*[\"']?#)", re.IGNORECASE)),
)

# Un tag termina al primo `>` FUORI dalle virgolette: `aria-label="a > b"`
# non lo spezza, così gli attributi che seguono restano nella scansione.
_TAG_RE = re.compile(r"<(?:[^>\"']|\"[^\"]*\"|'[^']*')*>")
_STYLE_BODY_RE = re.compile(r"<\s*style\b[^>]*>(.*?)<\s*/\s*style\s*>", re.IGNORECASE | re.DOTALL)
# Gli attributi `aria-*` (Vega: `aria-label="Title text 'vedi url(x)'"`)
# ripetono titoli e valori dei dati dentro il tag: sono testo inerte e non
# entrano nella scansione, come il testo dei nodi.
_ARIA_ATTR_RE = re.compile(r"\saria-[a-z]+\s*=\s*(?:\"[^\"]*\"|'[^']*')", re.IGNORECASE)


def iter_tag_contents(body: str) -> Iterator[str]:
    """Contenuto dei tag `<…>` di un SVG (delimitatori compresi), con gli
    attributi `aria-*` rimossi. È l'unica parte del documento in cui un
    riferimento esterno è davvero un attributo: il testo dei nodi
    (`<text>`, `<tspan>`, `<title>`) non compare mai, così una label che
    parla di `url(https://…)` resta contenuto legittimo. Riusata dal
    controllo degli SVG Mermaid, che non passano da `normalize_svg`."""
    for raw_tag in _TAG_RE.findall(body):
        yield _ARIA_ATTR_RE.sub("", raw_tag)


def iter_style_bodies(body: str) -> Iterator[str]:
    """Corpo dei blocchi `<style>…</style>`: CSS a tutti gli effetti,
    quindi soggetto alle stesse regole degli attributi `style`."""
    yield from _STYLE_BODY_RE.findall(body)


def _scan_forbidden(body: str) -> str | None:
    """Ritorna l'etichetta del primo contenuto non ammesso, `None` se pulito."""
    for label, pattern in _FORBIDDEN_GLOBAL:
        if pattern.search(body):
            return label
    for tag in iter_tag_contents(body):
        for label, pattern in (*_FORBIDDEN_IN_TAG, *_FORBIDDEN_CSS):
            if pattern.search(tag):
                return label
    for css in iter_style_bodies(body):
        for label, pattern in _FORBIDDEN_CSS:
            if pattern.search(css):
                return f"{label} in <style>"
    return None


# --- radice ---------------------------------------------------------------

_ROOT_RE = re.compile(r"<svg\b([^>]*)>", re.IGNORECASE | re.DOTALL)
_ATTR_RE = re.compile(r"([A-Za-z_:][-A-Za-z0-9_:.]*)\s*=\s*(?:\"([^\"]*)\"|'([^']*)')", re.DOTALL)
_LENGTH_RE = re.compile(r"^\s*([+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?)\s*([a-z%]*)\s*$")
_MAX_WIDTH_RE = re.compile(r"max-width\s*:[^;]*;?", re.IGNORECASE)
_NUMBER_RE = re.compile(r"[+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?")

_UNIT_TO_PX = {
    "": 1.0,
    "px": 1.0,
    "pt": 96.0 / 72.0,
    "pc": 16.0,
    "mm": 96.0 / 25.4,
    "cm": 96.0 / 2.54,
    "in": 96.0,
}


def _length_px(value: str | None) -> float | None:
    """Lunghezza CSS/SVG in px; `None` per assente, percentuale o unità
    non convertibile (em/ex dipendono dal font)."""
    if value is None:
        return None
    m = _LENGTH_RE.match(value)
    if not m:
        return None
    unit = m.group(2).lower()
    factor = _UNIT_TO_PX.get(unit)
    if factor is None:
        return None
    px = float(m.group(1)) * factor
    return px if px > 0 else None


def _fmt(value: float) -> str:
    text = f"{value:.2f}".rstrip("0").rstrip(".")
    return text or "0"


def _parse_viewbox(value: str | None) -> tuple[float, float, float, float] | None:
    if not value:
        return None
    nums = _NUMBER_RE.findall(value)
    if len(nums) != 4:
        return None
    x, y, w, h = (float(n) for n in nums)
    if w <= 0 or h <= 0:
        return None
    return x, y, w, h


def _attr_string(attrs: list[tuple[str, str]]) -> str:
    return "".join(f' {k}="{v}"' for k, v in attrs)


# --- letture per la banda di leggibilità (D10) ----------------------------


@dataclass(frozen=True)
class SvgBox:
    """Geometria della radice: viewBox in unità utente, dimensione
    intrinseca in px se la radice la dichiara (`None` per `width="100%"`) e
    `px_per_unit = width_px / vb_w` (1.0 per gli SVG fluidi; 4/3 per DOT e
    matplotlib, le cui unità utente sono pt)."""

    vb_w: float
    vb_h: float
    width_px: float | None
    height_px: float | None
    px_per_unit: float


def _root_attrs(svg: str) -> dict[str, str] | None:
    """Attributi del tag radice, con i nomi in minuscolo; `None` senza `<svg>`."""
    root = _ROOT_RE.search(svg or "")
    if root is None:
        return None
    out: dict[str, str] = {}
    for m in _ATTR_RE.finditer(root.group(1)):
        value = m.group(2) if m.group(2) is not None else (m.group(3) or "")
        out[m.group(1).lower()] = value
    return out


def svg_intrinsic_box(svg: str) -> SvgBox | None:
    """`SvgBox` della radice (stessa regola di `normalize_svg`: senza
    `viewBox` valgono `width`/`height` numerici); `None` se non
    determinabile (nessuna radice, viewBox degenere, sola larghezza in
    percentuale). Mirror di `svgIntrinsicBox` nel frontend."""
    attrs = _root_attrs(svg)
    if attrs is None:
        return None
    width_px = _length_px(attrs.get("width"))
    height_px = _length_px(attrs.get("height"))
    viewbox = _parse_viewbox(attrs.get("viewbox"))
    if viewbox is None and width_px is not None and height_px is not None:
        viewbox = (0.0, 0.0, width_px, height_px)
    if viewbox is None:
        return None
    _x, _y, vb_w, vb_h = viewbox
    px_per_unit = width_px / vb_w if width_px is not None else 1.0
    return SvgBox(
        vb_w=vb_w, vb_h=vb_h, width_px=width_px, height_px=height_px, px_per_unit=px_per_unit
    )


# --- corpo dei testi: cascata CSS minima per `font-size` -------------------
#
# Lettura statica senza parser XML né motore CSS: una scansione dei nodi
# (tag con le virgolette rispettate, testo, commenti, CDATA) con la pila
# degli elementi aperti, e le sole regole dei blocchi `<style>` che
# dichiarano `font-size`. Selettori coperti: composti `tipo`/`*`, `#id`,
# `.classe` uniti da discendente o `>` (tutto ciò che Mermaid emette, pie e
# radar compresi); pseudo-classi dinamiche e pseudo-elementi non
# corrispondono mai in un render statico. Qualunque altra dichiarazione di
# corpo (selettori con attributi, `+`, `~`, `:not()`, regole annidate o
# dentro una at-rule, shorthand `font:`) e ogni valore che dipende dal
# contesto (`rem`, parole chiave, `var()`, `calc()`, `em`/`%` senza un
# antenato che dichiari il corpo) rendono la lettura irrisolta: ripiego
# sulla costante di formato, loggato, mai un valore inventato. `ex` e
# `ch` dipendono dal font: valgono come limite inferiore
# (`_EX_CH_MIN_EM`), che basta quando il testo non può essere il minimo
# (il titolo `4ex` del timeline di Mermaid).

_NODE_RE = re.compile(
    r"<!--.*?-->"
    r"|<!\[CDATA\[(?P<cdata>.*?)\]\]>"
    r"|<[!?][^>]*>"
    r"|<(?P<close>/)?(?P<name>[A-Za-z_][\w:.-]*)"
    r"(?P<attrs>(?:[^>\"']|\"[^\"]*\"|'[^']*')*?)(?P<void>/)?\s*>"
    r"|(?P<text>[^<]+)",
    re.DOTALL,
)
_RAW_TEXT_END_RE = {
    "style": re.compile(r"<\s*/\s*style\s*>", re.IGNORECASE),
    "script": re.compile(r"<\s*/\s*script\s*>", re.IGNORECASE),
}
_FONT_SIZE_DECL_RE = re.compile(
    r"(?:^|;)\s*font-size\s*:\s*([^;!]*?)\s*(!\s*important\s*)?(?=;|$)", re.IGNORECASE
)
_FONT_SHORTHAND_RE = re.compile(r"(?:^|[;{])\s*font\s*:", re.IGNORECASE)
_CSS_NOISE_RE = re.compile(r"/\*.*?\*/|<!\[CDATA\[|\]\]>|<!--|-->", re.DOTALL)
_SELECTOR_TOKEN_RE = re.compile(r"\s*>\s*|\s+|[^\s>]+")
_COMPOUND_RE = re.compile(
    r"(?P<tag>\*|[A-Za-z_][\w-]*)?(?P<sel>(?:[#.][\w-]+)*)(?P<pseudo>(?:::?[\w-]+)*)"
)
_PSEUDO_RE = re.compile(r"(::?)([\w-]+)")
# Stati d'interazione: in un `<img>` o in un PDF non si verificano mai
# (`:visited` non può comunque cambiare il corpo).
_DYNAMIC_PSEUDO = frozenset(
    {"hover", "focus", "active", "visited", "target", "focus-within", "focus-visible"}
)
# Limite inferiore di `1ex` e `1ch` in em per le famiglie del tema (x-height
# 0,536 em in Noto Sans, 0,547 in DejaVu Sans; «0» largo 0,57-0,64 em).
_EX_CH_MIN_EM = 0.4


@dataclass(frozen=True)
class _Compound:
    tag: str | None  # None = universale
    # Token che il nodo deve portare tutti: "t:tipo", "#id", ".classe".
    tokens: frozenset[str]
    specificity: tuple[int, int, int]  # (id, classi, tipi)


@dataclass(frozen=True)
class _FontRule:
    parts: tuple[_Compound, ...]  # da sinistra a destra
    combinators: tuple[str, ...]  # fra parts[i] e parts[i + 1]: " " oppure ">"
    # Chiave di cascata: (important, inline, foglio, id, classi, tipi, ordine).
    key: tuple[int, ...]
    value: str
    # Token richiesti agli antenati (condizione necessaria, scarto rapido).
    scope: frozenset[str]


@dataclass(frozen=True)
class _Font:
    uu: float  # corpo in unità utente (limite inferiore se non esatto)
    from_sheet: bool  # dal `<style>` (anche per eredità) invece che dai tag
    exact: bool = True  # False per `ex`/`ch` e per chi li eredita


@dataclass
class _Node:
    tag: str
    tokens: frozenset[str]
    attrs: dict[str, str]
    scope: frozenset[str] = frozenset()  # token di tutti gli antenati
    # Calcolato solo per i nodi con testo o con testo fra i discendenti;
    # None se nessun antenato dichiara il corpo (valore iniziale sconosciuto).
    font: _Font | None = None
    resolved: bool = False
    has_text: bool = False


def _unescape(text: str) -> str:
    """`html.unescape` che non solleva (gemello di quello di `graph_rules`):
    `&#` seguito da più cifre del limite di conversione degli interi
    (4.300) dà `ValueError`, e il testo resta com'è. Graphviz ricopia il
    riferimento tale e quale in `id` e `class`: la lettura non deve
    costare la figura, né le altre del batch."""
    with contextlib.suppress(ValueError):
        return html.unescape(text)
    return text


def _tag_attrs(raw: str) -> dict[str, str]:
    """Attributi di un tag in scansione sequenziale (un `font-size=` dentro
    il valore di un `aria-label` resta valore), nomi in minuscolo, valori
    con le entità risolte come nel DOM."""
    out: dict[str, str] = {}
    for m in _ATTR_RE.finditer(raw):
        value = m.group(2) if m.group(2) is not None else (m.group(3) or "")
        out.setdefault(m.group(1).lower(), _unescape(value))
    return out


def _last_font_size(block: str) -> tuple[str, bool] | None:
    """Dichiarazione `font-size` che vince nel blocco: l'ultima, e fra le
    `!important` l'ultima importante."""
    found: tuple[str, bool] | None = None
    for m in _FONT_SIZE_DECL_RE.finditer(block):
        important = m.group(2) is not None
        if found is None or important or not found[1]:
            found = (m.group(1), important)
    return found


def _node_tokens(tag: str | None, ids: list[str], classes: list[str]) -> frozenset[str]:
    tokens = {f"#{i}" for i in ids} | {f".{c}" for c in classes}
    if tag is not None:
        tokens.add(f"t:{tag}")
    return frozenset(tokens)


def _parse_selector(selector: str) -> tuple[tuple[_Compound, ...], tuple[str, ...]] | None:
    """Selettore nella grammatica coperta; `None` se fuori grammatica,
    `((), ())` se non può corrispondere in un render statico."""
    parts: list[_Compound] = []
    combinators: list[str] = []
    pending: str | None = None
    never = False
    for token in _SELECTOR_TOKEN_RE.findall(selector.strip()):
        if not token.strip():
            pending = pending or " "
            continue
        if token.strip() == ">":
            if not parts or pending == ">":
                return None
            pending = ">"
            continue
        m = _COMPOUND_RE.fullmatch(token)
        if m is None:
            return None
        for colons, name in _PSEUDO_RE.findall(m.group("pseudo")):
            if colons == "::" or name.lower() in _DYNAMIC_PSEUDO:
                never = True
            else:
                return None
        sel = m.group("sel")
        raw_tag = m.group("tag")
        tag = None if raw_tag in (None, "*") else raw_tag.lower()
        ids = re.findall(r"#([\w-]+)", sel)
        classes = re.findall(r"\.([\w-]+)", sel)
        compound = _Compound(
            tag=tag,
            tokens=_node_tokens(tag, ids, classes),
            specificity=(len(ids), len(classes), int(tag is not None)),
        )
        if parts:
            combinators.append(pending or " ")
        pending = None
        parts.append(compound)
    if not parts or pending == ">":
        return None
    if never:
        return (), ()
    return tuple(parts), tuple(combinators)


def _matching_brace(css: str, open_at: int) -> int:
    depth = 0
    for i in range(open_at, len(css)):
        if css[i] == "{":
            depth += 1
        elif css[i] == "}":
            depth -= 1
            if depth == 0:
                return i
    return len(css)


def _style_font_rules(svg: str) -> tuple[dict[str | None, list[_FontRule]], bool]:
    """Regole dei blocchi `<style>` che dichiarano il corpo, indicizzate per
    tipo del composto più a destra (`None` = universale); il secondo valore
    è vero se una dichiarazione di corpo sta fuori dalla grammatica
    coperta."""
    rules: dict[str | None, list[_FontRule]] = {}
    unsupported = False
    order = 0
    for raw in iter_style_bodies(svg):
        css = _CSS_NOISE_RE.sub(" ", raw)
        pos = 0
        while (open_at := css.find("{", pos)) >= 0:
            close_at = _matching_brace(css, open_at)
            prelude = css[pos:open_at].rsplit(";", 1)[-1].strip()
            block = css[open_at + 1 : close_at]
            pos = close_at + 1
            sets_size = "font-size" in block.lower() or bool(_FONT_SHORTHAND_RE.search(block))
            if not sets_size:
                continue
            if prelude.startswith("@"):
                # `@media`/`@supports` condizionano il corpo, `@keyframes`
                # lo anima nei frame video: nessuno dei due è statico.
                unsupported = True
                continue
            if "{" in block or _FONT_SHORTHAND_RE.search(block):
                unsupported = True
                continue
            decl = _last_font_size(block)
            if decl is None:
                continue
            for selector in prelude.split(","):
                parsed = _parse_selector(selector)
                if parsed is None:
                    unsupported = True
                    continue
                parts, combinators = parsed
                if not parts:
                    continue
                order += 1
                spec = [sum(p.specificity[k] for p in parts) for k in range(3)]
                key = (int(decl[1]), 0, 1, *spec, order)
                scope = frozenset().union(*(p.tokens for p in parts[:-1]))
                rule = _FontRule(parts, combinators, key, decl[0], scope)
                rules.setdefault(parts[-1].tag, []).append(rule)
    return rules, unsupported


def _rule_matches(rule: _FontRule, chain: list[_Node]) -> bool:
    """Confronto da destra a sinistra con ritorno sui discendenti."""
    if not (rule.parts[-1].tokens <= chain[-1].tokens and rule.scope <= chain[-1].scope):
        return False

    def match(part: int, at: int) -> bool:
        if not rule.parts[part].tokens <= chain[at].tokens:
            return False
        if part == 0:
            return True
        if rule.combinators[part - 1] == ">":
            return at > 0 and match(part - 1, at - 1)
        return any(match(part - 1, k) for k in range(at - 1, -1, -1))

    return match(len(rule.parts) - 1, len(chain) - 1)


def _resolve_font(raw: str, from_sheet: bool, parent: _Font | None) -> tuple[_Font | None, bool]:
    """Valore calcolato della dichiarazione vincente e vero se calcolabile:
    lunghezze assolute in unità utente, `em`/`%` rispetto al padre, `ex`/
    `ch` come limite inferiore (`_EX_CH_MIN_EM` em del padre), `inherit`/
    `unset` il padre; nessun valore per zero (testo invisibile). Un
    relativo senza antenati dichiarati, `rem`, parole chiave, `var()` e
    `calc()` dipendono dal contesto (il corpo del contenitore HTML o i
    16 px della radice di un `<img>`): il nodo prosegue col padre ma la
    lettura è irrisolta."""
    value = raw.strip().lower()
    if value in ("inherit", "unset"):
        return parent, True
    m = _LENGTH_RE.match(value)
    if m is None:
        return parent, False
    number = float(m.group(1))
    unit = m.group(2)
    if number <= 0:
        return None, number == 0
    if unit in ("em", "%", "ex", "ch"):
        if parent is None:
            return None, False
        if unit in ("ex", "ch"):
            return _Font(parent.uu * number * _EX_CH_MIN_EM, parent.from_sheet, False), True
        factor = number / (100.0 if unit == "%" else 1.0)
        return _Font(parent.uu * factor, parent.from_sheet, parent.exact), True
    px = _length_px(value)
    if px is None:
        return parent, False
    return _Font(px, from_sheet), True


def _node_font(
    chain: list[_Node], rules: dict[str | None, list[_FontRule]], parent: _Font | None
) -> tuple[_Font | None, bool]:
    """Corpo calcolato dell'ultimo nodo di `chain` e vero se la sua
    dichiarazione è fuori grammatica (shorthand `font:` in linea, valore
    non calcolabile). Cascata: `!important`, poi `style` in linea, poi
    regole del foglio per specificità e ordine, poi l'attributo di
    presentazione `font-size` (specificità zero), altrimenti il padre."""
    attrs = chain[-1].attrs
    best: tuple[tuple[int, ...], str, bool] | None = None
    presentation = attrs.get("font-size")
    if presentation is not None:
        best = ((0, 0, 0, 0, 0, 0, 0), presentation, False)
    for rule in (*rules.get(chain[-1].tag, ()), *rules.get(None, ())):
        if (best is None or rule.key > best[0]) and _rule_matches(rule, chain):
            best = (rule.key, rule.value, True)
    style = attrs.get("style")
    unsupported = False
    if style is not None:
        unsupported = bool(_FONT_SHORTHAND_RE.search(style))
        inline = _last_font_size(style)
        if inline is not None:
            key = (int(inline[1]), 1, 0, 0, 0, 0, 0)
            if best is None or key > best[0]:
                best = (key, inline[0], False)
    if best is None:
        return parent, unsupported
    font, computable = _resolve_font(best[1], best[2], parent)
    return font, unsupported or not computable


def _resolve_chain(stack: list[_Node], rules: dict[str | None, list[_FontRule]]) -> bool:
    """Calcola, dall'alto, il corpo dei nodi della pila non ancora risolti;
    vero se uno di essi ha una dichiarazione fuori grammatica."""
    odd = False
    for i, node in enumerate(stack):
        if node.resolved:
            continue
        parent = stack[i - 1] if i else None
        if parent is not None:
            node.scope = parent.scope | parent.tokens
        node.font, bad = _node_font(stack[: i + 1], rules, parent.font if parent else None)
        node.resolved = True
        odd = odd or bad
    return odd


def svg_base_font_px(svg: str) -> SvgMetrics:
    """Metriche del testo di contenuto: corpo calcolato di ogni `<text>`/
    `<tspan>` con testo proprio non vuoto (un nodo di testo figlio diretto,
    come `__measureSvgFontPx`), con la cascata minima descritta sopra:
    attributi e `style` in linea (Vega-Lite, DOT, matplotlib), regole del
    `<style>` per id, classe e discendenza (Mermaid: radice `#id{…}`,
    `.slice` del pie, `.radarAxisLabel` del radar) ed eredità dal padre
    (lo `style` del `<text>` che contiene i `<tspan>` del sequence). Valori
    in px CSS alla dimensione naturale (`× px_per_unit`).

    `source="parsed"` se il minimo viene dagli attributi o dallo `style`
    in linea (anche ereditati), `"root_rule"` se dal foglio di stile
    dell'SVG, `"unresolved"` se nessun testo ha un valore esatto, se una
    dichiarazione di corpo è fuori grammatica o dipende dal contesto, o se
    un testo in `ex`/`ch` potrebbe stare sotto il minimo esatto (la
    mediana, diagnostica, usa il limite inferiore); `"no_text"` senza
    testi. Per Mermaid resta il ripiego della misura in Chromium.
    Differenze dichiarate dal DOM: lo `display:none` non è filtrato;
    `<defs>`/`<symbol>`/`<clipPath>` non sono esclusi (nessun renderer
    nostro vi mette testo). Non tocca l'SVG."""
    body = svg or ""
    rules, unsupported = _style_font_rules(body)
    box = svg_intrinsic_box(body)
    ppu = box.px_per_unit if box is not None else 1.0

    stack: list[_Node] = []
    texts: list[_Node] = []
    pos = 0
    while pos < len(body):
        m = _NODE_RE.match(body, pos)
        if m is None:
            pos += 1
            continue
        pos = m.end()
        text = m.group("text") if m.group("cdata") is None else m.group("cdata")
        if text is not None:
            if stack and stack[-1].tag in ("text", "tspan") and _unescape(text).strip():
                stack[-1].has_text = True
            continue
        name = m.group("name")
        if name is None:
            continue
        tag = name.rsplit(":", 1)[-1].lower()
        if m.group("close"):
            for i in range(len(stack) - 1, -1, -1):
                if stack[i].tag == tag:
                    del stack[i:]
                    break
            continue
        if tag in _RAW_TEXT_END_RE:
            if not m.group("void"):
                end = _RAW_TEXT_END_RE[tag].search(body, pos)
                pos = end.end() if end is not None else len(body)
            continue
        if m.group("void"):
            continue  # nessun testo proprio né discendenti: corpo irrilevante
        attrs = _tag_attrs(m.group("attrs"))
        elem_id = attrs.get("id")
        node = _Node(
            tag=tag,
            tokens=_node_tokens(tag, [elem_id] if elem_id else [], attrs.get("class", "").split()),
            attrs=attrs,
        )
        stack.append(node)
        if tag in ("text", "tspan"):
            texts.append(node)
            unsupported = _resolve_chain(stack, rules) or unsupported

    counted = [n for n in texts if n.has_text]
    if not counted:
        return SvgMetrics(None, None, 0, "no_text")
    values = [n.font for n in counted if n.font is not None]
    exact = [v for v in values if v.exact]
    if unsupported or not exact:
        return SvgMetrics(None, None, len(counted), "unresolved")
    minimum = min(exact, key=lambda v: (v.uu, v.from_sheet))
    if any(v.uu < minimum.uu for v in values if not v.exact):
        return SvgMetrics(None, None, len(counted), "unresolved")
    median = statistics.median(v.uu for v in values)
    source: MetricsSource = "root_rule" if minimum.from_sheet else "parsed"
    return SvgMetrics(minimum.uu * ppu, median * ppu, len(counted), source)


def normalize_svg(svg: str, *, max_bytes: int) -> NormalizedSvg:
    """Normalizza l'SVG di un renderer nostro. Solleva `SvgRejectedError`
    con il motivo; non tenta mai una sanificazione parziale."""
    if len(svg.encode("utf-8")) > max_bytes:
        raise SvgRejectedError(f"svg oltre {max_bytes} byte")

    body = svg.lstrip("\ufeff")
    body = _PROLOGUE_RE.sub("", body, count=1)

    forbidden = _scan_forbidden(body)
    if forbidden is not None:
        raise SvgRejectedError(f"contenuto non ammesso: {forbidden}")

    root = _ROOT_RE.search(body)
    if root is None:
        raise SvgRejectedError("tag radice <svg> assente")

    attrs: list[tuple[str, str]] = []
    for m in _ATTR_RE.finditer(root.group(1)):
        name = m.group(1)
        value = m.group(2) if m.group(2) is not None else (m.group(3) or "")
        attrs.append((name, value.replace('"', "&quot;")))
    by_name = {k.lower(): v for k, v in attrs}

    width_px = _length_px(by_name.get("width"))
    height_px = _length_px(by_name.get("height"))
    viewbox = _parse_viewbox(by_name.get("viewbox"))
    if viewbox is None and width_px is not None and height_px is not None:
        viewbox = (0.0, 0.0, width_px, height_px)
    if viewbox is not None:
        _x, _y, vb_w, vb_h = viewbox
        if width_px is None and height_px is None:
            width_px, height_px = vb_w, vb_h
        elif width_px is None and height_px is not None:
            width_px = height_px * vb_w / vb_h
        elif height_px is None and width_px is not None:
            height_px = width_px * vb_h / vb_w

    kept: list[tuple[str, str]] = []
    has_xmlns = False
    has_xlink_ns = False
    for name, value in attrs:
        lname = name.lower()
        if lname in ("width", "height", "viewbox", "preserveaspectratio"):
            continue
        if lname == "style":
            cleaned = _MAX_WIDTH_RE.sub("", value).strip().strip(";").strip()
            if cleaned:
                kept.append((name, cleaned))
            continue
        if lname == "xmlns":
            has_xmlns = True
        if lname == "xmlns:xlink":
            has_xlink_ns = True
        kept.append((name, value))

    root_attrs: list[tuple[str, str]] = []
    if not has_xmlns:
        root_attrs.append(("xmlns", SVG_NS))
    if not has_xlink_ns and "xlink:" in body:
        root_attrs.append(("xmlns:xlink", XLINK_NS))
    root_attrs.extend(kept)
    if width_px is not None and height_px is not None:
        root_attrs.append(("width", _fmt(width_px)))
        root_attrs.append(("height", _fmt(height_px)))
    if viewbox is not None:
        root_attrs.append(("viewBox", " ".join(_fmt(v) for v in viewbox)))
    root_attrs.append(("preserveAspectRatio", "xMidYMid meet"))

    new_root = "<svg" + _attr_string(root_attrs) + ">"
    normalized = body[: root.start()] + new_root + body[root.end() :]
    return NormalizedSvg(svg=normalized.strip(), width_px=width_px, height_px=height_px)


def svg_to_data_uri(svg: str) -> str:
    """Converte un SVG in `data:image/svg+xml;base64,...` per `<img src>`.
    Base64 perché l'SVG contiene molti `"` (viewBox, xmlns, ...) che
    romperebbero un `src="..."` HTML se URL-encodato troppo
    permissivamente. Condivisa da PDF slide, PDF dispensa e frame video."""
    payload = base64.b64encode(svg.encode("utf-8")).decode("ascii")
    return f"data:image/svg+xml;base64,{payload}"


__all__ = [
    "NormalizedSvg",
    "SvgBox",
    "SvgRejectedError",
    "normalize_svg",
    "svg_base_font_px",
    "svg_intrinsic_box",
    "svg_to_data_uri",
]
