"""Normalizzazione degli SVG prodotti dai renderer server-side (Q3).

Modulo puro (regex sul solo tag radice + scansione del documento): nessun
parser XML, nessuna dipendenza dal resto dell'applicazione. Vale per gli SVG
di vl-convert (Vega-Lite), Graphviz `dot` e matplotlib (`function`); gli SVG
Mermaid NON passano da qui (la loro catena resta byte-identica, A11).

Regole:
1. oltre `max_bytes` → `SvgRejectedError`;
2. prologo rimosso: BOM, `<?xml …?>`, `<!DOCTYPE …>`, commenti iniziali
   («Created with matplotlib», «Generated by graphviz»: determinismo fra
   versioni e date);
3. scansione che RIFIUTA (i renderer sono nostri: un'anomalia è un
   fallback, non una sanificazione parziale). Globale sul documento per
   gli elementi attivi, animati o esterni: `<script`, `<foreignObject`,
   `<iframe`, `<image`, `<set`, `<animate*`, `<handler` (SMIL può
   riscrivere `href` o `on*` a tempo di esecuzione; nessun renderer nostro
   li emette), anche con prefisso di namespace (`<svg:script`). Limitata
   al contenuto dei tag `<…>` (attributi) per `<use`
   con href non-frammento, gestori `on*=`, `href` esterni (quotati o no),
   `javascript:`, `data:text/html`, `@import`, `url()` non-frammento; le
   stesse regole CSS valgono dentro `<style>…</style>`. Il riconoscimento
   del tag rispetta le virgolette: un `>` dentro un valore quotato
   (`aria-label="a > b"`) non chiude il tag e gli attributi successivi
   vengono scanditi. Il testo dei nodi (label, tick, `<title>`) NON è
   scandito: una label «vedi url(x)» o un tick «href=» sono contenuti
   legittimi. I `<use xlink:href="#m…">` e i `<clipPath>` interni di
   matplotlib passano;
4. tag radice: `viewBox` letto o costruito, `width`/`height` convertiti in
   px (`pt×96/72`, `mm×96/25.4`, `in×96`) e RISCRITTI come dimensione
   intrinseca dell'`<img>` (`max-width:100%` riduce ma non ingrandisce: un
   grafo DOT a tre nodi resta piccolo), `preserveAspectRatio="xMidYMid
   meet"`, `max-width` rimosso dallo `style`, `xmlns` garantito. Nessun
   namespacing degli id: ogni `<img>` è un documento isolato.

Due letture pure per la banda di leggibilità (D10, `figure_scale`), valide
anche per gli SVG Mermaid perché non li modificano: `svg_intrinsic_box`
(viewBox, dimensione intrinseca e `px_per_unit` della radice) e
`svg_base_font_px` (corpo minimo dei testi di contenuto dagli attributi
`font-size`/`style` dei `<text>`/`<tspan>` e dalla regola radice
`#id{font-size}`).
"""

from __future__ import annotations

import base64
import re
import statistics
from collections.abc import Iterator
from dataclasses import dataclass

from app.services.figure_scale import MetricsSource, SvgMetrics

SVG_NS = "http://www.w3.org/2000/svg"
XLINK_NS = "http://www.w3.org/1999/xlink"


class SvgRejectedError(ValueError):
    """L'SVG non è accettabile (dimensione, contenuto attivo, radice mancante)."""


@dataclass(frozen=True)
class NormalizedSvg:
    svg: str
    width_px: float | None
    height_px: float | None


# --- prologo -------------------------------------------------------------

_PROLOGUE_RE = re.compile(
    r"^(?:\s*(?:<\?xml[^>]*\?>|<!DOCTYPE(?:[^>\[]|\[[^\]]*\])*>|<!--.*?-->))*\s*",
    re.DOTALL | re.IGNORECASE,
)

# --- scansione ----------------------------------------------------------

# Elementi rifiutati ovunque compaiano: sono attivi (script), animati
# (set, animate*, handler: SMIL può assegnare `href` o `on*` a tempo di
# esecuzione), portano HTML (foreignObject, iframe) o risorse
# esterne/raster (image). `function_plot` non produce mai `<image>`
# nonostante `svg.image_inline` nei rcParams (contour e fill_between sono
# path; niente imshow). Il nome dell'elemento può portare un prefisso di
# namespace (`<svg:script>`, `<x:foreignObject>`): stesso elemento per un
# parser XML, stesso rifiuto.
_NS_PREFIX = r"<\s*(?:[A-Za-z_][\w.-]*:)?"
_FORBIDDEN_GLOBAL: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("script", re.compile(_NS_PREFIX + r"script\b", re.IGNORECASE)),
    ("foreignObject", re.compile(_NS_PREFIX + r"foreignObject\b", re.IGNORECASE)),
    ("iframe", re.compile(_NS_PREFIX + r"iframe\b", re.IGNORECASE)),
    ("image", re.compile(_NS_PREFIX + r"image\b", re.IGNORECASE)),
    ("set", re.compile(_NS_PREFIX + r"set\b", re.IGNORECASE)),
    ("animate", re.compile(_NS_PREFIX + r"animate[a-z]*\b", re.IGNORECASE)),
    ("handler", re.compile(_NS_PREFIX + r"handler\b", re.IGNORECASE)),
)

# `href` esterno: valore quotato che non inizia con `#`, oppure valore non
# quotato (`href=http://x`) che non è un frammento.
_EXTERNAL_HREF = r"\bhref\s*=\s*(?:[\"']\s*(?!#)|(?![\"'\s#]))"

# Pattern applicati SOLO al contenuto dei tag `<…>` (attributi), non al
# testo dei nodi: una label «vedi url(x)» è testo legittimo, un attributo
# `style="…url(http://…)"` no.
_FORBIDDEN_IN_TAG: tuple[tuple[str, re.Pattern[str]], ...] = (
    (
        "use con href esterno",
        re.compile(r"^<\s*use\b[^>]*" + _EXTERNAL_HREF, re.IGNORECASE),
    ),
    ("gestore di evento", re.compile(r"(?<![\w-])on[a-z]+\s*=", re.IGNORECASE)),
    ("href esterno", re.compile(_EXTERNAL_HREF, re.IGNORECASE)),
)

# Pattern CSS/URI: valgono negli attributi e dentro i blocchi `<style>`.
_FORBIDDEN_CSS: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("javascript:", re.compile(r"javascript\s*:", re.IGNORECASE)),
    ("data:text/html", re.compile(r"data\s*:\s*text/html", re.IGNORECASE)),
    ("@import", re.compile(r"@import\b", re.IGNORECASE)),
    ("url() esterno", re.compile(r"\burl\((?!\s*[\"']?#)", re.IGNORECASE)),
)

# Un tag termina al primo `>` FUORI dalle virgolette: `aria-label="a > b"`
# non lo spezza, così gli attributi che seguono restano nella scansione.
_TAG_RE = re.compile(r"<(?:[^>\"']|\"[^\"]*\"|'[^']*')*>")
_STYLE_BODY_RE = re.compile(r"<\s*style\b[^>]*>(.*?)<\s*/\s*style\s*>", re.IGNORECASE | re.DOTALL)
# Gli attributi `aria-*` (Vega: `aria-label="Title text 'vedi url(x)'"`)
# ripetono titoli e valori dei dati dentro il tag: sono testo inerte e non
# entrano nella scansione, come il testo dei nodi.
_ARIA_ATTR_RE = re.compile(r"\saria-[a-z]+\s*=\s*(?:\"[^\"]*\"|'[^']*')", re.IGNORECASE)


def iter_tag_contents(body: str) -> Iterator[str]:
    """Contenuto dei tag `<…>` di un SVG (delimitatori compresi), con gli
    attributi `aria-*` rimossi. È l'unica parte del documento in cui un
    riferimento esterno è davvero un attributo: il testo dei nodi
    (`<text>`, `<tspan>`, `<title>`) non compare mai, così una label che
    parla di `url(https://…)` resta contenuto legittimo. Riusata dal
    controllo degli SVG Mermaid, che non passano da `normalize_svg`."""
    for raw_tag in _TAG_RE.findall(body):
        yield _ARIA_ATTR_RE.sub("", raw_tag)


def iter_style_bodies(body: str) -> Iterator[str]:
    """Corpo dei blocchi `<style>…</style>`: CSS a tutti gli effetti,
    quindi soggetto alle stesse regole degli attributi `style`."""
    yield from _STYLE_BODY_RE.findall(body)


def _scan_forbidden(body: str) -> str | None:
    """Ritorna l'etichetta del primo contenuto non ammesso, `None` se pulito."""
    for label, pattern in _FORBIDDEN_GLOBAL:
        if pattern.search(body):
            return label
    for tag in iter_tag_contents(body):
        for label, pattern in (*_FORBIDDEN_IN_TAG, *_FORBIDDEN_CSS):
            if pattern.search(tag):
                return label
    for css in iter_style_bodies(body):
        for label, pattern in _FORBIDDEN_CSS:
            if pattern.search(css):
                return f"{label} in <style>"
    return None


# --- radice ---------------------------------------------------------------

_ROOT_RE = re.compile(r"<svg\b([^>]*)>", re.IGNORECASE | re.DOTALL)
_ATTR_RE = re.compile(r"([A-Za-z_:][-A-Za-z0-9_:.]*)\s*=\s*(?:\"([^\"]*)\"|'([^']*)')", re.DOTALL)
_LENGTH_RE = re.compile(r"^\s*([+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?)\s*([a-z%]*)\s*$")
_MAX_WIDTH_RE = re.compile(r"max-width\s*:[^;]*;?", re.IGNORECASE)
_NUMBER_RE = re.compile(r"[+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?")

_UNIT_TO_PX = {
    "": 1.0,
    "px": 1.0,
    "pt": 96.0 / 72.0,
    "pc": 16.0,
    "mm": 96.0 / 25.4,
    "cm": 96.0 / 2.54,
    "in": 96.0,
}


def _length_px(value: str | None) -> float | None:
    """Lunghezza CSS/SVG in px; `None` per assente, percentuale o unità
    non convertibile (em/ex dipendono dal font)."""
    if value is None:
        return None
    m = _LENGTH_RE.match(value)
    if not m:
        return None
    unit = m.group(2).lower()
    factor = _UNIT_TO_PX.get(unit)
    if factor is None:
        return None
    px = float(m.group(1)) * factor
    return px if px > 0 else None


def _fmt(value: float) -> str:
    text = f"{value:.2f}".rstrip("0").rstrip(".")
    return text or "0"


def _parse_viewbox(value: str | None) -> tuple[float, float, float, float] | None:
    if not value:
        return None
    nums = _NUMBER_RE.findall(value)
    if len(nums) != 4:
        return None
    x, y, w, h = (float(n) for n in nums)
    if w <= 0 or h <= 0:
        return None
    return x, y, w, h


def _attr_string(attrs: list[tuple[str, str]]) -> str:
    return "".join(f' {k}="{v}"' for k, v in attrs)


# --- letture per la banda di leggibilità (D10) ----------------------------


@dataclass(frozen=True)
class SvgBox:
    """Geometria della radice: viewBox in unità utente, dimensione
    intrinseca in px se la radice la dichiara (`None` per `width="100%"`) e
    `px_per_unit = width_px / vb_w` (1.0 per gli SVG fluidi; 4/3 per DOT e
    matplotlib, le cui unità utente sono pt)."""

    vb_w: float
    vb_h: float
    width_px: float | None
    height_px: float | None
    px_per_unit: float


def _root_attrs(svg: str) -> dict[str, str] | None:
    """Attributi del tag radice, con i nomi in minuscolo; `None` senza `<svg>`."""
    root = _ROOT_RE.search(svg or "")
    if root is None:
        return None
    out: dict[str, str] = {}
    for m in _ATTR_RE.finditer(root.group(1)):
        value = m.group(2) if m.group(2) is not None else (m.group(3) or "")
        out[m.group(1).lower()] = value
    return out


def svg_intrinsic_box(svg: str) -> SvgBox | None:
    """`SvgBox` della radice (stessa regola di `normalize_svg`: senza
    `viewBox` valgono `width`/`height` numerici); `None` se non
    determinabile (nessuna radice, viewBox degenere, sola larghezza in
    percentuale). Mirror di `svgIntrinsicBox` nel frontend."""
    attrs = _root_attrs(svg)
    if attrs is None:
        return None
    width_px = _length_px(attrs.get("width"))
    height_px = _length_px(attrs.get("height"))
    viewbox = _parse_viewbox(attrs.get("viewbox"))
    if viewbox is None and width_px is not None and height_px is not None:
        viewbox = (0.0, 0.0, width_px, height_px)
    if viewbox is None:
        return None
    _x, _y, vb_w, vb_h = viewbox
    px_per_unit = width_px / vb_w if width_px is not None else 1.0
    return SvgBox(
        vb_w=vb_w, vb_h=vb_h, width_px=width_px, height_px=height_px, px_per_unit=px_per_unit
    )


# Tag `<text>`/`<tspan>` con lo stesso trattamento delle virgolette di
# `_TAG_RE`; il gruppo 3 è il testo proprio fino al tag successivo, quindi
# in `<text><tspan>x</tspan></text>` conta lo `tspan`, non il `text`.
_TEXT_TAG_RE = re.compile(
    r"<(text|tspan)\b((?:[^>\"']|\"[^\"]*\"|'[^']*')*)>([^<]*)", re.IGNORECASE
)
_FONT_SIZE_ATTR_RE = re.compile(
    r"(?<![\w-])font-size\s*=\s*(?:\"([^\"]*)\"|'([^']*)')", re.IGNORECASE
)
_STYLE_ATTR_RE = re.compile(r"(?<![\w-])style\s*=\s*(?:\"([^\"]*)\"|'([^']*)')", re.IGNORECASE)
_FONT_SIZE_DECL_RE = re.compile(r"(?:^|;)\s*font-size\s*:\s*([^;!]+)", re.IGNORECASE)


def _attr_value(pattern: re.Pattern[str], tag_attrs: str) -> str | None:
    m = pattern.search(tag_attrs)
    if m is None:
        return None
    return m.group(1) if m.group(1) is not None else (m.group(2) or "")


def _own_font_px(tag_attrs: str) -> float | None:
    """Corpo proprio del tag in unità utente: `font-size:` dentro `style`
    vince sull'attributo (precedenza CSS); `em`/`ex`/`%` non sono
    risolvibili e valgono «nessun valore proprio»."""
    style = _attr_value(_STYLE_ATTR_RE, tag_attrs)
    if style is not None:
        decl = _FONT_SIZE_DECL_RE.search(style)
        if decl is not None:
            return _length_px(decl.group(1))
    return _length_px(_attr_value(_FONT_SIZE_ATTR_RE, tag_attrs))


def _root_rule_font_px(svg: str, root_id: str | None) -> float | None:
    """`font-size` della regola il cui selettore è ESATTAMENTE `#<id>` (non
    `#<id> svg`, non `#<id> .x`) nei blocchi `<style>`; l'ultima vince."""
    if not root_id:
        return None
    rule_re = re.compile(r"(?<![\w#.-])#" + re.escape(root_id) + r"\s*\{([^}]*)\}")
    found: float | None = None
    for css in iter_style_bodies(svg):
        for rule in rule_re.finditer(css):
            decl = _FONT_SIZE_DECL_RE.search(rule.group(1))
            if decl is not None:
                value = _length_px(decl.group(1))
                if value is not None:
                    found = value
    return found


def svg_base_font_px(svg: str) -> SvgMetrics:
    """Metriche del testo di contenuto lette dagli attributi (Vega-Lite,
    DOT, matplotlib) e, come secondo canale, dalla regola radice `#id{…}`
    (Mermaid). Conta solo i tag con testo proprio non vuoto; un tag senza
    valore proprio eredita la regola radice se esiste. Valori in px CSS
    alla dimensione naturale (`× px_per_unit`).

    Per Mermaid la regola radice è SBAGLIATA su `pie` (17) e `radar` (12,
    classi nello `<style>` invisibili a una regex): è solo il fallback
    della misura in Chromium e viaggia con `source="root_rule"`. Non
    esclude `<defs>`/`<symbol>`/`<clipPath>`: nessun renderer nostro vi
    mette testo. Non tocca l'SVG."""
    attrs = _root_attrs(svg)
    root_px = _root_rule_font_px(svg, attrs.get("id") if attrs else None)
    box = svg_intrinsic_box(svg)
    ppu = box.px_per_unit if box is not None else 1.0

    values: list[tuple[float, bool]] = []  # (uu, dal tag)
    count = 0
    for m in _TEXT_TAG_RE.finditer(svg or ""):
        if not m.group(3).strip():
            continue
        count += 1
        own = _own_font_px(m.group(2))
        if own is not None:
            values.append((own, True))
        elif root_px is not None:
            values.append((root_px, False))
    if count == 0:
        return SvgMetrics(None, None, 0, "no_text")
    if not values:
        return SvgMetrics(None, None, count, "unresolved")
    minimum = min(values, key=lambda v: (v[0], not v[1]))
    median = statistics.median(v for v, _own in values)
    source: MetricsSource = "parsed" if minimum[1] else "root_rule"
    return SvgMetrics(minimum[0] * ppu, median * ppu, count, source)


def normalize_svg(svg: str, *, max_bytes: int) -> NormalizedSvg:
    """Normalizza l'SVG di un renderer nostro. Solleva `SvgRejectedError`
    con il motivo; non tenta mai una sanificazione parziale."""
    if len(svg.encode("utf-8")) > max_bytes:
        raise SvgRejectedError(f"svg oltre {max_bytes} byte")

    body = svg.lstrip("\ufeff")
    body = _PROLOGUE_RE.sub("", body, count=1)

    forbidden = _scan_forbidden(body)
    if forbidden is not None:
        raise SvgRejectedError(f"contenuto non ammesso: {forbidden}")

    root = _ROOT_RE.search(body)
    if root is None:
        raise SvgRejectedError("tag radice <svg> assente")

    attrs: list[tuple[str, str]] = []
    for m in _ATTR_RE.finditer(root.group(1)):
        name = m.group(1)
        value = m.group(2) if m.group(2) is not None else (m.group(3) or "")
        attrs.append((name, value.replace('"', "&quot;")))
    by_name = {k.lower(): v for k, v in attrs}

    width_px = _length_px(by_name.get("width"))
    height_px = _length_px(by_name.get("height"))
    viewbox = _parse_viewbox(by_name.get("viewbox"))
    if viewbox is None and width_px is not None and height_px is not None:
        viewbox = (0.0, 0.0, width_px, height_px)
    if viewbox is not None:
        _x, _y, vb_w, vb_h = viewbox
        if width_px is None and height_px is None:
            width_px, height_px = vb_w, vb_h
        elif width_px is None and height_px is not None:
            width_px = height_px * vb_w / vb_h
        elif height_px is None and width_px is not None:
            height_px = width_px * vb_h / vb_w

    kept: list[tuple[str, str]] = []
    has_xmlns = False
    has_xlink_ns = False
    for name, value in attrs:
        lname = name.lower()
        if lname in ("width", "height", "viewbox", "preserveaspectratio"):
            continue
        if lname == "style":
            cleaned = _MAX_WIDTH_RE.sub("", value).strip().strip(";").strip()
            if cleaned:
                kept.append((name, cleaned))
            continue
        if lname == "xmlns":
            has_xmlns = True
        if lname == "xmlns:xlink":
            has_xlink_ns = True
        kept.append((name, value))

    root_attrs: list[tuple[str, str]] = []
    if not has_xmlns:
        root_attrs.append(("xmlns", SVG_NS))
    if not has_xlink_ns and "xlink:" in body:
        root_attrs.append(("xmlns:xlink", XLINK_NS))
    root_attrs.extend(kept)
    if width_px is not None and height_px is not None:
        root_attrs.append(("width", _fmt(width_px)))
        root_attrs.append(("height", _fmt(height_px)))
    if viewbox is not None:
        root_attrs.append(("viewBox", " ".join(_fmt(v) for v in viewbox)))
    root_attrs.append(("preserveAspectRatio", "xMidYMid meet"))

    new_root = "<svg" + _attr_string(root_attrs) + ">"
    normalized = body[: root.start()] + new_root + body[root.end() :]
    return NormalizedSvg(svg=normalized.strip(), width_px=width_px, height_px=height_px)


def svg_to_data_uri(svg: str) -> str:
    """Converte un SVG in `data:image/svg+xml;base64,...` per `<img src>`.
    Base64 perché l'SVG contiene molti `"` (viewBox, xmlns, ...) che
    romperebbero un `src="..."` HTML se URL-encodato troppo
    permissivamente. Condivisa da PDF slide, PDF dispensa e frame video."""
    payload = base64.b64encode(svg.encode("utf-8")).decode("ascii")
    return f"data:image/svg+xml;base64,{payload}"


__all__ = [
    "NormalizedSvg",
    "SvgBox",
    "SvgRejectedError",
    "normalize_svg",
    "svg_base_font_px",
    "svg_intrinsic_box",
    "svg_to_data_uri",
]
