"""Normalizzazione degli SVG prodotti dai renderer server-side (Q3).

Modulo puro (regex sul solo tag radice + scansione del documento): nessun
parser XML, nessuna dipendenza dal resto dell'applicazione. Vale per gli SVG
di vl-convert (Vega-Lite), Graphviz `dot` e matplotlib (`function`); gli SVG
Mermaid NON passano da qui (la loro catena resta byte-identica, A11).

Regole:
1. oltre `max_bytes` → `SvgRejectedError`;
2. prologo rimosso: BOM, `<?xml …?>`, `<!DOCTYPE …>`, commenti iniziali
   («Created with matplotlib», «Generated by graphviz»: determinismo fra
   versioni e date);
3. scansione che RIFIUTA (i renderer sono nostri: un'anomalia è un
   fallback, non una sanificazione parziale). Globale sul documento per
   gli elementi attivi, animati o esterni: `<script`, `<foreignObject`,
   `<iframe`, `<image`, `<set`, `<animate*`, `<handler` (SMIL può
   riscrivere `href` o `on*` a tempo di esecuzione; nessun renderer nostro
   li emette), anche con prefisso di namespace (`<svg:script`). Limitata
   al contenuto dei tag `<…>` (attributi) per `<use`
   con href non-frammento, gestori `on*=`, `href` esterni (quotati o no),
   `javascript:`, `data:text/html`, `@import`, `url()` non-frammento; le
   stesse regole CSS valgono dentro `<style>…</style>`. Il riconoscimento
   del tag rispetta le virgolette: un `>` dentro un valore quotato
   (`aria-label="a > b"`) non chiude il tag e gli attributi successivi
   vengono scanditi. Il testo dei nodi (label, tick, `<title>`) NON è
   scandito: una label «vedi url(x)» o un tick «href=» sono contenuti
   legittimi. I `<use xlink:href="#m…">` e i `<clipPath>` interni di
   matplotlib passano;
4. tag radice: `viewBox` letto o costruito, `width`/`height` convertiti in
   px (`pt×96/72`, `mm×96/25.4`, `in×96`) e RISCRITTI come dimensione
   intrinseca dell'`<img>` (`max-width:100%` riduce ma non ingrandisce: un
   grafo DOT a tre nodi resta piccolo), `preserveAspectRatio="xMidYMid
   meet"`, `max-width` rimosso dallo `style`, `xmlns` garantito. Nessun
   namespacing degli id: ogni `<img>` è un documento isolato.
"""

from __future__ import annotations

import base64
import re
from collections.abc import Iterator
from dataclasses import dataclass

SVG_NS = "http://www.w3.org/2000/svg"
XLINK_NS = "http://www.w3.org/1999/xlink"


class SvgRejectedError(ValueError):
    """L'SVG non è accettabile (dimensione, contenuto attivo, radice mancante)."""


@dataclass(frozen=True)
class NormalizedSvg:
    svg: str
    width_px: float | None
    height_px: float | None


# --- prologo -------------------------------------------------------------

_PROLOGUE_RE = re.compile(
    r"^(?:\s*(?:<\?xml[^>]*\?>|<!DOCTYPE(?:[^>\[]|\[[^\]]*\])*>|<!--.*?-->))*\s*",
    re.DOTALL | re.IGNORECASE,
)

# --- scansione ----------------------------------------------------------

# Elementi rifiutati ovunque compaiano: sono attivi (script), animati
# (set, animate*, handler: SMIL può assegnare `href` o `on*` a tempo di
# esecuzione), portano HTML (foreignObject, iframe) o risorse
# esterne/raster (image). `function_plot` non produce mai `<image>`
# nonostante `svg.image_inline` nei rcParams (contour e fill_between sono
# path; niente imshow). Il nome dell'elemento può portare un prefisso di
# namespace (`<svg:script>`, `<x:foreignObject>`): stesso elemento per un
# parser XML, stesso rifiuto.
_NS_PREFIX = r"<\s*(?:[A-Za-z_][\w.-]*:)?"
_FORBIDDEN_GLOBAL: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("script", re.compile(_NS_PREFIX + r"script\b", re.IGNORECASE)),
    ("foreignObject", re.compile(_NS_PREFIX + r"foreignObject\b", re.IGNORECASE)),
    ("iframe", re.compile(_NS_PREFIX + r"iframe\b", re.IGNORECASE)),
    ("image", re.compile(_NS_PREFIX + r"image\b", re.IGNORECASE)),
    ("set", re.compile(_NS_PREFIX + r"set\b", re.IGNORECASE)),
    ("animate", re.compile(_NS_PREFIX + r"animate[a-z]*\b", re.IGNORECASE)),
    ("handler", re.compile(_NS_PREFIX + r"handler\b", re.IGNORECASE)),
)

# `href` esterno: valore quotato che non inizia con `#`, oppure valore non
# quotato (`href=http://x`) che non è un frammento.
_EXTERNAL_HREF = r"\bhref\s*=\s*(?:[\"']\s*(?!#)|(?![\"'\s#]))"

# Pattern applicati SOLO al contenuto dei tag `<…>` (attributi), non al
# testo dei nodi: una label «vedi url(x)» è testo legittimo, un attributo
# `style="…url(http://…)"` no.
_FORBIDDEN_IN_TAG: tuple[tuple[str, re.Pattern[str]], ...] = (
    (
        "use con href esterno",
        re.compile(r"^<\s*use\b[^>]*" + _EXTERNAL_HREF, re.IGNORECASE),
    ),
    ("gestore di evento", re.compile(r"(?<![\w-])on[a-z]+\s*=", re.IGNORECASE)),
    ("href esterno", re.compile(_EXTERNAL_HREF, re.IGNORECASE)),
)

# Pattern CSS/URI: valgono negli attributi e dentro i blocchi `<style>`.
_FORBIDDEN_CSS: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("javascript:", re.compile(r"javascript\s*:", re.IGNORECASE)),
    ("data:text/html", re.compile(r"data\s*:\s*text/html", re.IGNORECASE)),
    ("@import", re.compile(r"@import\b", re.IGNORECASE)),
    ("url() esterno", re.compile(r"\burl\((?!\s*[\"']?#)", re.IGNORECASE)),
)

# Un tag termina al primo `>` FUORI dalle virgolette: `aria-label="a > b"`
# non lo spezza, così gli attributi che seguono restano nella scansione.
_TAG_RE = re.compile(r"<(?:[^>\"']|\"[^\"]*\"|'[^']*')*>")
_STYLE_BODY_RE = re.compile(r"<\s*style\b[^>]*>(.*?)<\s*/\s*style\s*>", re.IGNORECASE | re.DOTALL)
# Gli attributi `aria-*` (Vega: `aria-label="Title text 'vedi url(x)'"`)
# ripetono titoli e valori dei dati dentro il tag: sono testo inerte e non
# entrano nella scansione, come il testo dei nodi.
_ARIA_ATTR_RE = re.compile(r"\saria-[a-z]+\s*=\s*(?:\"[^\"]*\"|'[^']*')", re.IGNORECASE)


def iter_tag_contents(body: str) -> Iterator[str]:
    """Contenuto dei tag `<…>` di un SVG (delimitatori compresi), con gli
    attributi `aria-*` rimossi. È l'unica parte del documento in cui un
    riferimento esterno è davvero un attributo: il testo dei nodi
    (`<text>`, `<tspan>`, `<title>`) non compare mai, così una label che
    parla di `url(https://…)` resta contenuto legittimo. Riusata dal
    controllo degli SVG Mermaid, che non passano da `normalize_svg`."""
    for raw_tag in _TAG_RE.findall(body):
        yield _ARIA_ATTR_RE.sub("", raw_tag)


def iter_style_bodies(body: str) -> Iterator[str]:
    """Corpo dei blocchi `<style>…</style>`: CSS a tutti gli effetti,
    quindi soggetto alle stesse regole degli attributi `style`."""
    yield from _STYLE_BODY_RE.findall(body)


def _scan_forbidden(body: str) -> str | None:
    """Ritorna l'etichetta del primo contenuto non ammesso, `None` se pulito."""
    for label, pattern in _FORBIDDEN_GLOBAL:
        if pattern.search(body):
            return label
    for tag in iter_tag_contents(body):
        for label, pattern in (*_FORBIDDEN_IN_TAG, *_FORBIDDEN_CSS):
            if pattern.search(tag):
                return label
    for css in iter_style_bodies(body):
        for label, pattern in _FORBIDDEN_CSS:
            if pattern.search(css):
                return f"{label} in <style>"
    return None


# --- radice ---------------------------------------------------------------

_ROOT_RE = re.compile(r"<svg\b([^>]*)>", re.IGNORECASE | re.DOTALL)
_ATTR_RE = re.compile(r"([A-Za-z_:][-A-Za-z0-9_:.]*)\s*=\s*(?:\"([^\"]*)\"|'([^']*)')", re.DOTALL)
_LENGTH_RE = re.compile(r"^\s*([+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?)\s*([a-z%]*)\s*$")
_MAX_WIDTH_RE = re.compile(r"max-width\s*:[^;]*;?", re.IGNORECASE)
_NUMBER_RE = re.compile(r"[+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?")

_UNIT_TO_PX = {
    "": 1.0,
    "px": 1.0,
    "pt": 96.0 / 72.0,
    "pc": 16.0,
    "mm": 96.0 / 25.4,
    "cm": 96.0 / 2.54,
    "in": 96.0,
}


def _length_px(value: str | None) -> float | None:
    """Lunghezza CSS/SVG in px; `None` per assente, percentuale o unità
    non convertibile (em/ex dipendono dal font)."""
    if value is None:
        return None
    m = _LENGTH_RE.match(value)
    if not m:
        return None
    unit = m.group(2).lower()
    factor = _UNIT_TO_PX.get(unit)
    if factor is None:
        return None
    px = float(m.group(1)) * factor
    return px if px > 0 else None


def _fmt(value: float) -> str:
    text = f"{value:.2f}".rstrip("0").rstrip(".")
    return text or "0"


def _parse_viewbox(value: str | None) -> tuple[float, float, float, float] | None:
    if not value:
        return None
    nums = _NUMBER_RE.findall(value)
    if len(nums) != 4:
        return None
    x, y, w, h = (float(n) for n in nums)
    if w <= 0 or h <= 0:
        return None
    return x, y, w, h


def _attr_string(attrs: list[tuple[str, str]]) -> str:
    return "".join(f' {k}="{v}"' for k, v in attrs)


def normalize_svg(svg: str, *, max_bytes: int) -> NormalizedSvg:
    """Normalizza l'SVG di un renderer nostro. Solleva `SvgRejectedError`
    con il motivo; non tenta mai una sanificazione parziale."""
    if len(svg.encode("utf-8")) > max_bytes:
        raise SvgRejectedError(f"svg oltre {max_bytes} byte")

    body = svg.lstrip("\ufeff")
    body = _PROLOGUE_RE.sub("", body, count=1)

    forbidden = _scan_forbidden(body)
    if forbidden is not None:
        raise SvgRejectedError(f"contenuto non ammesso: {forbidden}")

    root = _ROOT_RE.search(body)
    if root is None:
        raise SvgRejectedError("tag radice <svg> assente")

    attrs: list[tuple[str, str]] = []
    for m in _ATTR_RE.finditer(root.group(1)):
        name = m.group(1)
        value = m.group(2) if m.group(2) is not None else (m.group(3) or "")
        attrs.append((name, value.replace('"', "&quot;")))
    by_name = {k.lower(): v for k, v in attrs}

    width_px = _length_px(by_name.get("width"))
    height_px = _length_px(by_name.get("height"))
    viewbox = _parse_viewbox(by_name.get("viewbox"))
    if viewbox is None and width_px is not None and height_px is not None:
        viewbox = (0.0, 0.0, width_px, height_px)
    if viewbox is not None:
        _x, _y, vb_w, vb_h = viewbox
        if width_px is None and height_px is None:
            width_px, height_px = vb_w, vb_h
        elif width_px is None and height_px is not None:
            width_px = height_px * vb_w / vb_h
        elif height_px is None and width_px is not None:
            height_px = width_px * vb_h / vb_w

    kept: list[tuple[str, str]] = []
    has_xmlns = False
    has_xlink_ns = False
    for name, value in attrs:
        lname = name.lower()
        if lname in ("width", "height", "viewbox", "preserveaspectratio"):
            continue
        if lname == "style":
            cleaned = _MAX_WIDTH_RE.sub("", value).strip().strip(";").strip()
            if cleaned:
                kept.append((name, cleaned))
            continue
        if lname == "xmlns":
            has_xmlns = True
        if lname == "xmlns:xlink":
            has_xlink_ns = True
        kept.append((name, value))

    root_attrs: list[tuple[str, str]] = []
    if not has_xmlns:
        root_attrs.append(("xmlns", SVG_NS))
    if not has_xlink_ns and "xlink:" in body:
        root_attrs.append(("xmlns:xlink", XLINK_NS))
    root_attrs.extend(kept)
    if width_px is not None and height_px is not None:
        root_attrs.append(("width", _fmt(width_px)))
        root_attrs.append(("height", _fmt(height_px)))
    if viewbox is not None:
        root_attrs.append(("viewBox", " ".join(_fmt(v) for v in viewbox)))
    root_attrs.append(("preserveAspectRatio", "xMidYMid meet"))

    new_root = "<svg" + _attr_string(root_attrs) + ">"
    normalized = body[: root.start()] + new_root + body[root.end() :]
    return NormalizedSvg(svg=normalized.strip(), width_px=width_px, height_px=height_px)


def svg_to_data_uri(svg: str) -> str:
    """Converte un SVG in `data:image/svg+xml;base64,...` per `<img src>`.
    Base64 perché l'SVG contiene molti `"` (viewBox, xmlns, ...) che
    romperebbero un `src="..."` HTML se URL-encodato troppo
    permissivamente. Condivisa da PDF slide, PDF dispensa e frame video."""
    payload = base64.b64encode(svg.encode("utf-8")).decode("ascii")
    return f"data:image/svg+xml;base64,{payload}"


__all__ = ["NormalizedSvg", "SvgRejectedError", "normalize_svg", "svg_to_data_uri"]
